import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import {FaThreads} from "react-icons/fa6";
import {FaGithub} from "react-icons/fa";
import React from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "garamdale",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${inter.className} bg-background text-primary`}>
    <Navbar/>
    <main className="relative container mx-auto px-4 pt-16">
      <div className="relative z-10">
        {children}
      </div>
    </main>
    <footer className="bg-opacity-90 py-4 text-center mt-16 border-t border-gray-200">
      <div className="text-center mb-4">
        <h3 className="text-xl font-semibold mb-4">Follow Me</h3>
        <div className="flex justify-center space-x-4">
          <Link href="https://www.threads.net/@garamhoon" target="_blank" rel="noopener noreferrer">
            <FaThreads/>
          </Link>
          <Link href="https://github.com/garamhoon" target="_blank" rel="noopener noreferrer">
            <FaGithub/>
          </Link>
        </div>
      </div>
      <p>&copy; {new Date().getFullYear()} garamdale. All rights reserved.</p>
    </footer>
    </body>
    </html>
  );
}
