import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import Navbar from '@/components/Navbar';
import React from 'react';
import { ThemeProvider } from 'next-themes';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'garamdale',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background text-primary`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <div className="min-h-screen bg-background text-foreground">
            <main className="container mx-auto px-4 py-8">{children}</main>
          </div>
          <footer className="mt-16 border-t py-6 text-center text-sm">
            <p>&copy; {new Date().getFullYear()} garamdale. All rights reserved.</p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
